name: run-clang-format

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 1
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: 'dyn-opt include lib'
        exclude: 'test'
        clangFormatVersion: 11
        style: llvm
